name: "Infra-deployment"
run-name: Infra-deployment of ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Which branch to deploy?'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - feature
  

      Env:
        description: 'Select environment to deploy to'
        required: true
        type: choice
        options:
          - prod
          - stage
          - dev


jobs:
  terraform:
    name: teraformInit
    runs-on: self-hosted
    steps:
    -  name: Dhondhu mahraj
       run: echo Dhondhu mahraj
