name: "Infra-deployment"

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - 'feature/**'

jobs:
  terraform:
    name: teraformInit
    runs-on: self-hosted
    steps:
    -  name: Dhondhu mahraj
       run: echo Dhondhu mahraj
